spring.application.name=coffee-reservation

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=Roasthouse


admin.default.email=${ADMIN_EMAIL:admin@roasthouse.com}
admin.default.password=${ADMIN_PASSWORD:Admin@123}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false

otp.expiry.minutes=5
auth.token.expiry.hours=12

logging.level.com.abikumar.coffee_reservation=INFO 
logging.level.org.springframework.jdbc.core=WARN